{% set version = "0.9.1.post0" %}

package:
  name: pythran
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pythran/pythran-{{ version }}.tar.gz
  sha256: 2c3d3be03d2b4338f7a82a52217f7ddf9f37bfacf17aeb66e5fc883a29e06535

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  skip: true  # [win and py27]
  entry_points:
    - pythran = pythran.run:run
    - pythran-config = pythran.config:run

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy >=1.13
    - pytest-runner
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - decorator
    - gast
    - networkx >=2
    - ply >=3.4
    - six

test:
  files:
    - dprod.py
  requires:
    - {{ compiler('cxx') }}
  commands:
    - pythran dprod.py
    - python -c 'import dprod'
test:
  imports:
    - omp
    - pythran
    - pythran.analyses
    - pythran.optimizations
    - pythran.transformations
    - pythran.types

about:
  home: http://github.com/serge-sans-paille/pythran
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'a claimless python to c++ converter'

  description: |
    Pythran is an ahead of time compiler for a subset of the Python language,
    with a focus on scientific computing. It takes a Python module annotated
    with a few interface description and turns it into a native Python module
    with the same interface, but (hopefully) faster.
  doc_url: https://pythran.readthedocs.io/
  dev_url: https://github.com/serge-sans-paille/pythran

extra:
  recipe-maintainers:
    - saraedum
    - serge-sans-paille
