{% set version = "0.9.9" %}

package:
  name: pythran
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pythran/pythran-{{ version }}.tar.gz
  sha256: aaabc97f30ad46d1d62303323de6697d2933779afa4666c15b0f433cb50825b1

build:
  number: 1
  script:
    - python -c "import os, shutil; shutil.rmtree(os.path.join('pythran', 'xsimd'))"
    - "python -c \"with open('setup.cfg', 'w') as s: s.write('[build_py]\\nno_xsimd=True')\""  # [not win]
    - python -m pip install . --no-deps -vv
  entry_points:
    - pythran = pythran.run:run
    - pythran-config = pythran.config:run

requirements:
  build:
    - {{ compiler('cxx') }}  # [not win]
    - clang                  # [win]
    - clangxx                # [win]
  host:
    - python
    - pip
    - numpy
    - pytest-runner
  run:
    - {{ compiler('cxx') }}  # [not win]
    - clang                  # [win]
    - clangxx                # [win]
    - python
    - {{ pin_compatible('numpy') }}
    - decorator
    - gast ~=0.4.0
    - networkx >=2
    - ply >=3.4
    - six
    - beniget ~=0.3.0
    - xsimd                  # [not win]

test:
  files:
    - dprod.py
    - simple_numexpr.py
  commands:
    - pythran -v dprod.py
    - python -c "import dprod"
    - pythran -v simple_numexpr.py -DUSE_XSIMD -march=native
    - python -c "import simple_numexpr"
  imports:
    - omp  # [not win]
    - pythran
    - pythran.analyses
    - pythran.optimizations
    - pythran.transformations
    - pythran.types

about:
  home: http://github.com/serge-sans-paille/pythran
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: a claimless python to c++ converter

  description: |
    Pythran is an ahead of time compiler for a subset of the Python language,
    with a focus on scientific computing. It takes a Python module annotated
    with a few interface description and turns it into a native Python module
    with the same interface, but (hopefully) faster.
  doc_url: https://pythran.readthedocs.io/
  dev_url: https://github.com/serge-sans-paille/pythran

extra:
  recipe-maintainers:
    - saraedum
    - serge-sans-paille
