appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Dv2rhV5NZqzJQvzBkrYpMndzStcof2O+RqPpsyFZQv8e8xmL2Pgdg6sYKz7EV0hdBFFu+mGHUrDtGVWEV+6ESngdVOV6dqmez2/2joiLLsI7YmEupWJTkLSgx++8cuL7crBmzKS+otoMyAEZS+JI27c15CU3Ws2lSqxWlCgY622LI5nuhcj1R/ijoFmLdWb3jnIk0Lq6FO1cJdnv9MI4dfX9I0p+8miY9SiunJthS+ZTA7uSc5ZBv24F35/qSfSnz9/ag8LKbpb5eCHvDXtzusMpbyTFlP2e2BYRYLb82YQ8+Rkwh7kw+nl/aTnjQFIPUm8G38QfzXRkNXZR2GIGHKuLt/kXKkXEqiDqpT5b2sZw0UyRjma+XuUF7TM/bEX9xN1ufep98/VEzR89oBR4fKL3w6mncC1APXISdj+apX8+sQPVX7H5RLGziF5Ow+AR4gsq6gzoFbwctj4Xs9GnWjnXuoLKFV8xnAO1hCxosU6mBu6KJy3B3XJ413QDGmdY9WpHvuu83/42CwDoDAUsMczw0+3tX14d8UfoG8U8kNKHf90POaNRFQNyPR/a2XJMBeBEaXNPZ5VjiuWjNYwA83Fjq2IdstDrI+0P4h6TJHp9MZJolpOLKZyTRywM6HbySJC0t1DZpzESEqPplOqsZnnzw+tk+CCwe2MgpZpDPXI=}
