travis:
  secure:
    BINSTAR_TOKEN: oB8eSlECEUiJtyqNeEV1RCKh/ETng6q5voTz4m/FNgt/sb4+m5zAiPpMnQkpMmpItnOGeA+lHbIBOAZAxnb5fjZutT0wZXM5j+/ynhwLRP5aipB4eNZYsaFhTtYGabFwlYTf4SoSpzH80lpx7Eck/fUa63gd57KiaglyVINM5F9MnliXqZ5YZS5sBcgz6/urgZ9lRuqGE9pz+k5ux0J8l8D6R95qtg5dVXoqbjmTZW86mqzPBLfmvVvVkVBCLpzwooM9ZVZQpjjB4pBMEQ6uVI8D+XJux3fkefB1Mw7e52Ln5gPMcRsjbnJHf48txKVG5k6DO7nw8Ufzud74Smg5TmLUHsCyDa7Ul1bBWz1YcerXYuNZ/dPofJAL1sh2Sv3i3txNzbdSobYwtx3zPeQrEXypzkZI2/6y3uzcfogc7fNa/bXfxaLRSEd38KnsaiakSFq4oL5E8KhYS5O2kR6jhDlWnDs9/Z15FKPEr8Ybp21uuTTHVCUfqRrQDG7Nze5j9tiMOel66F8dQcJL7L19KV8WQqzoV+WyEJJMGZ7Bh7pC9hinKpMZyNo/u2ZG1J42qMvVqbTCW8x8+FeuoEPHhD9wTB21Dunl3Ac1OjRb8mn7U+3SJYgnYSSzsnArSSfRqBTBXzTonOOnH/D5yTAkoUykkIhxySsl0juLDj5WvDk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
